version: "3"

services:
  linux-node:
    image: node:12.6.0
    entrypoint: bash
    working_dir: /usr/app
    volumes:
      - ./:/usr/app/
      - root_node_modules/:/usr/app/node_modules/
      - examples_basic_node_modules/:/usr/app/examples/basic/node_modules/

  basic-example:
    image: node:12.6.0
    command: npm start
    working_dir: /usr/app/examples/basic
    ports:
      - "4000:4000"
    volumes:
      - ./:/usr/app/
      - root_node_modules/:/usr/app/node_modules/
      - examples_basic_node_modules/:/usr/app/examples/basic/node_modules/

volumes:
  root_node_modules:
  examples_basic_node_modules:
