version: "3"

services:
  linux-node:
    image: node:12.6.0
    entrypoint: bash
    tty: true
    working_dir: /usr/app
    volumes:
      - ./:/usr/app/
      - root_node_modules/:/usr/app/node_modules/
      - test_artifacts/:/usr/app/tests/artifacts
      - experiments_node_modules/:/usr/app/experiments/node_modules/

  experiments:
    image: node:12.6.0
    command: npm start
    working_dir: /usr/app/experiments
    ports:
      - "4000:4000"
    volumes:
      - ./:/usr/app/
      - root_node_modules/:/usr/app/node_modules/
      - experiments_node_modules/:/usr/app/experiments/node_modules/

volumes:
  root_node_modules:
  experiments_node_modules:
  test_artifacts:
